class_path: base_model.MainModel
init_args:
  network: 
    class_path: models.erp.fova_depth_erp.FOVADepthERP
    init_args:
      height_width: [512,1536] 
      normalize_baseline: False
      greater_than_two_images: True
  criterion: 
    class_path: models.shared.criterion.Criterion
  image_logger: 
    class_path: models.shared.image_logger.ImageLogger
    init_args:
        log_freq: 1000 
        val_log_freq: 30
        distance_min_max: [0 , 50]
  test_metrics_processor:
    class_path: models.shared.test_metric_processor.TestMetricProcessor
  optimizer_config: 
    init_lr: 0.0001
    mile_stones: [10, 20]
    gamma: 0.1
  step_log_freq: 100