# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: CC-BY-NC-SA-4.0
#
# This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike
# 4.0 International License. https://creativecommons.org/licenses/by-nc-sa/4.0/

class_path: base_model.MainModel
init_args:
  network: 
    class_path: models.erp.fova_depth_erp.FOVADepthERP
  criterion: 
    class_path: models.shared.criterion.Criterion
  image_logger: 
    class_path: models.shared.image_logger.ImageLogger
    init_args:
        log_freq: 1000 
        val_log_freq: 30
        distance_min_max: [0 , 10]
  test_metrics_processor:
    class_path: models.shared.test_metric_processor.TestMetricProcessor
  optimizer_config: 
    init_lr: 0.0001
    mile_stones: [20, 40]
    gamma: 0.5
  step_log_freq: 100